### ISSUE TITLE
LogicApp engine is not calling the subscribe endpoint of my API, when I add and save the WebHook trigger

### ISSUE THREAD

**Issue by rnithish** [jeffhollan/LogicAppTriggersExample#2]
This is how my logic app WebHook trigger definition looks like in code. After I save it, I expect the http://logicappapitrigger.azurewebsites.net/api/webhooktrigger/subscribe endpoint of my API, which is hosted as an API app to be called with a valid callBack URL. But this is not happening.  

```
"triggers": {
    "Http_Webhook": {
        "conditions": [],
        "inputs": {
            "subscribe": {
                "body": "@listCallbackUrl()",
                "method": "POST",
                "uri": "http://logicappapitrigger.azurewebsites.net/api/webhooktrigger/subscribe"
            },
            "unsubscribe": {
                "body": "@listCallbackUrl()",
                "method": "POST",
                "uri": "http://logicappapitrigger.azurewebsites.net/api/webhooktrigger/unsubscribe/"
            }
        },
        "type": "HttpWebhook"
    }
}
```

}

**Comment by jeffhollan** [comment]
@rnithish how do you know the subscribe call is not happening?  If you change the URL to a [requestb.in](http://requestb.in) bucket do you see the calls come in?

**Comment by jeffhollan** [comment]
As an FYI the endpoint to trigger this sample is GET https://{hostname}.azurewebsitest.net/api/webhooktrigger/trigger

**Comment by rnithish** [comment]
@jeffhollan I was doing a live debugging of the API App and it was not hitting.

I found the issue now. The [FromBody] string callbackUrl parameter in the subscribe method was expecting a JSON body while from the LogicApp I guess text/plain was going in. 

So I removed this parameter and added string URL = Request.Content.ReadAsStringAsync().Result;

This worked. :+1: :)
